version: '3.8'

services:
  app:
    build: .
    container_name: nivu_payment_app
    ports:
      - "19245:19245"
    volumes:
      - ./data:/app/data
    environment:
      - PAYPHONE_TOKEN=${PAYPHONE_TOKEN}
      - PAYPHONE_STORE_ID=${PAYPHONE_STORE_ID}
      - PAYPHONE_CODING_PASSWORD=${PAYPHONE_CODING_PASSWORD}
    restart: always
